#!/bin/bash

# Download and Extract Maven
wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
tar -xzvf apache-maven-3.9.6-bin.tar.gz
rm -rf apache-maven-3.9.6-bin.tar.gz

# Move Maven to /opt
sudo mv apache-maven-3.9.6 /opt/
sudo mv /opt/apache-maven-3.9.6 /opt/maven3.9

# Set Environment Variables
export M2_HOME=/opt/maven3.9
export PATH=$PATH:$M2_HOME/bin

# Verify Maven Version
$M2_HOME/bin/mvn --version

source ~/.bashrc

